import "@/app/globals.css";
import { Header, Footer, Providers, ThemeSwitcher } from "@/app/components";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Telintec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="flex flex-col h-screen relative w-full overflow-x-hidden bg-bg dark:bg-bg-dark">
          <ThemeSwitcher />
          <Header />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
